export const onboardingAssets = {
  logoLight: require("../../assets/onboarding/dular-logo-light.png"),
  logoDark: require("../../assets/onboarding/dular-logo-dark.png"),
  splashBg: require("../../assets/onboarding/onboarding-splash-bg.png"),
  welcomeHero: require("../../assets/onboarding/onboarding-welcome-hero.png"),
  benefitsPhone: require("../../assets/onboarding/onboarding-benefits-phone.png"),
  securityShield: require("../../assets/onboarding/onboarding-security-shield.png"),
  startHero: require("../../assets/onboarding/onboarding-start-hero.png"),
  clientReviewCard: require("../../assets/onboarding/onboarding-card-client-review.png"),
  confirmedCard: require("../../assets/onboarding/onboarding-card-confirmed.png"),
  safescoreCard: require("../../assets/onboarding/onboarding-card-safescore.png"),
  heartIcon: require("../../assets/onboarding/onboarding-icon-heart.png"),
  calendarIcon: require("../../assets/onboarding/onboarding-icon-calendar.png"),
  shieldIcon: require("../../assets/onboarding/onboarding-icon-shield.png"),
  starIcon: require("../../assets/onboarding/onboarding-icon-star.png"),
  giftIcon: require("../../assets/onboarding/onboarding-icon-gift.png"),
} as const;
